# Generated by Django 4.2.20 on 2025-05-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author_name_book_pic_alter_book_book_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('cl', 'Classic'), ('ro', 'Romantic'), ('co', 'Comic'), ('fa', 'Fantasy'), ('ho', 'Horror'), ('ed', 'Educational')], default='cl', max_length=12),
        ),
    ]
